import cv2
import os


def rename_files_in_dir(dir_path:str, txt_to_remove:str,txt_to_insert:str):
    """Rename files in directory.

    Args:
        dir_path (str): _description_
        txt_to_remove (str): _description_
        txt_to_insert (str): _description_
    """
    for filename in os.listdir(dir_path):
        os.rename(filename, filename.replace('_2017.mp4', ''))


def convert_mp4_to_jpg(dir_path:str, txt_to_remove:str,txt_to_insert:str):
    """Converts MP4s to JPGs.

    Args:
        dir_path (str): _description_
        txt_to_remove (str): _description_
        txt_to_insert (str): _description_
    """
    # Read the video from specified path
    for filename in os.listdir(dir_path):
        cam = cv2.VideoCapture(filename)
        
        try:
            #Temporary fix for weird file names generated by Adobe
            dir_name = filename.replace(txt_to_remove,txt_to_insert)
            # creating a folder named data
            if not os.path.exists(dir_name):
                os.makedirs(dir_name)
        
        # if not created then raise error
        except OSError:
            print ('Error: Creating directory of data')
        
        # frame
        currentframe = 0
        
        while(True):
            
            # reading from frame
            ret,frame = cam.read()
        
            if ret:
                # if video is still left continue creating images
                name = './'+ dir_name +'/frame_' + str(currentframe) + '.jpg'
                print ('Creating...' + name)
        
                # writing the extracted images
                cv2.imwrite(name, frame)
        
                # increasing counter so that it will
                # show how many frames are created
                currentframe += 1
            else:
                break
        
        # Release all space and windows once done
        cam.release()
        cv2.destroyAllWindows()
        