roboflow_params:
  data_version: 2
  workspace: slalom
  project: tennis-object-detection
  data_format: yolov8
  write_dataset: datasets
  overwrite: False
  repo_name: yolo_tennis
training_params:  
  model: yolov8n.pt # choices="yolov8n","yolov8s","yolov8m","yolov8l","yolov8x"
  epochs: 1
  batch: 5
  imgsz: 640
mlflow_params:
  experiment_name: BestTennisDetector
  model_name: TennisDetector
  image_name: tennisdetector
  version: 0
  docker_port: 4000